# Site settings
title: Country Search
author:
  name: Katie Winthrop
  email: katiewin28@gmail.com
description: "Search for Info on different countries."

# Build settings
remote_theme: jekyll/minima
